server:
  port: 8083

spring:
  # 特定服务的数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/elm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: WJcsylsq142857

# MyBatis Plus特定配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: ynu.edu.service.business.entity

# 自定义配置
business:
  version: 1.0.0  # 版本号，用于测试配置刷新